version-tags: &version-tags
  tags:
    only: /\d+\.\d+(\.\d+|-(alpha|beta|rc|dev|post)\d+)/

version: 2.1
executors:
  python-container:
    docker:
      - image: quay.io/pypa/manylinux2014_x86_64
    working_directory: /home/circleci/project

jobs:
  pipeline:
    executor: python-container
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: "Install system dependencies"
          command: |
            yum update -y
            yum install -y epel-release
            yum install -y openssl-devel asio-devel
      - run:
          name: "Install python environment"
          command: |
            /opt/python/cp39-cp39/bin/python -m venv /home/circleci/venv
            source /home/circleci/venv/bin/activate
            pip install pytest black
            pip install -e .
      - run:
          name: "run formatter check"
          command: |
            source /home/circleci/venv/bin/activate
            black --check src/vroom
      - run:
          name: "run linting"
          command: |
            source /home/circleci/venv/bin/activate
            flake8 src/vroom
      - run:
          name: "Run tests"
          command: |
            source /home/circleci/venv/bin/activate
            pytest --doctest-modules test src/vroom
workflows:
  version: 2
  workflow:
    jobs:
      - pipeline:
          filters:
            <<: *version-tags
